from utils.race_weekends_order import race_orders, unique_races
from utils.sprint_weekends_order import sprint_orders, unique_sprints
from utils.practice_1_order import practice1_orders, unique_practice1
from utils.practice_2_order import practice2_orders, unique_practice2
from utils.practice_3_order import practice3_orders, unique_practice3